apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
#    type: Recreate
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - image: kbhatt23/hello-kubernetes:0.0.6
        imagePullPolicy: IfNotPresent
        name: hello-kubernetes
        ports:
        - name: liveness-port
          containerPort: 8089
          hostPort: 8089
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
  namespace: default
spec:
  #type: LoadBalancer
  ports:
  - port: 8089
    protocol: TCP
  selector:
    app: hello-kubernetes