apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-management-service-read
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-management-service-read
subjects:
- kind: ServiceAccount
  name: user-management-service
  namespace: default