spring.application.name=pranaam-kubernetes
server.port=8081

#random.number=1_23_43
random.number=12343


management.endpoints.web.exposure.include=httptrace,health

management.trace.http.include=RESPONSE_HEADERS,TIME_TAKEN