apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-kubernetes
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
# we need to give exact api url and not just root url        
            exact: /hello-kubernetes/test
      route:
        - destination:
            host: hello-kubernetes
            subset: v2
          weight: 100
      mirror:
        host: hello-kubernetes
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-kubernetes
spec:
  host: hello-kubernetes
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2