apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kbhatt23/user-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8081
        env:
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-host
        - name: RDS_PORT
          value: "3306"
        - name: RDS_DB
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-name
        - name: RDS_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-user
        - name: RDS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-password
                          
                                                       